
#
#FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS build
#WORKDIR webapp
#
#EXPOSE 80
#EXPOSE 5000
#
#
#COPY ["ProyectoPlazoletaComidasPlazoleta/ProyectoPlazoletaComidasPlazoleta.csproj", "ProyectoPlazoletaComidasPlazoleta/"]
#COPY ["Aplicacion/Aplicacion.csproj", "Aplicacion/"]
#COPY ["Dominio/Dominio.csproj", "Dominio/"]
#COPY ["Infraestructure/Infraestructure.csproj", "Infraestructure/"]
#RUN dotnet restore "ProyectoPlazoletaComidasPlazoleta/ProyectoPlazoletaComidasPlazoleta.csproj"
#
##copy ./*.csproj ./
#RUN dotnet restore
#
#
#copy . .
#RUN dotnet publish -c release -o out
#
#
#FROM mcr.microsoft.com/dotnet/aspnet:6.0
#WORKDIR /webapp
#copy --from=build /webapp/out .
#ENTRYPOINT ["dotnet", "ProyectoPlazoletaComidasPlazoleta.dll"]



FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS build
WORKDIR /app
EXPOSE 80
EXPOSE 5000

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["ProyectoPlazoletaComidasPlazoleta/ProyectoPlazoletaComidasPlazoleta.csproj", "ProyectoPlazoletaComidasPlazoleta/"]
COPY ["Aplicacion/Aplicacion.csproj", "Aplicacion/"]
COPY ["Dominio/Dominio.csproj", "Dominio/"]
COPY ["Infraestructure/Infraestructure.csproj", "Infraestructure/"]
RUN dotnet restore "ProyectoPlazoletaComidasPlazoleta/ProyectoPlazoletaComidasPlazoleta.csproj"
COPY . .
WORKDIR "/src/ProyectoPlazoletaComidasPlazoleta"
RUN dotnet build "ProyectoPlazoletaComidasPlazoleta.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ProyectoPlazoletaComidasPlazoleta.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ProyectoPlazoletaComidasPlazoleta.dll"]